### ISSUE TITLE
Updating python3 from 3.7.3 to 3.8+

### ISSUE THREAD

**Issue by Rhyzhang** [f0cal/google-coral#111]
Hi,

It seems `sudo add-apt-repository ppa:deadsnakes/ppa` does not work as I get this error:
```
WARNING:root:could not open file '/etc/apt/sources.list'

WARNING:root:could not open file '/etc/apt/sources.list'

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Mendel/eagle
```

Currently, Python3 on Mendel is running on Python 3.7.3 however matplotlib needs Python 3.8 in order to install. Do you know how I can update Python 3.7.3 to Python 3.8? 

Best,
Ryan

_Originally posted by @Rhyzhang in https://github.com/f0cal/google-coral/issues/10#issuecomment-1312605489_

**Comment by Rhyzhang** [comment]
I just downgraded matplotlib to a version that supported 3.7.3
