### ISSUE TITLE
Issue when installing MDT

### ISSUE THREAD

**Issue by libo-wu** [f0cal/google-coral#35]
* Doc you were trying to follow: https://coral.withgoogle.com/docs/dev-board/get-started/
* Your host OS: Linux
* Your Python3 version: 3.5.3

# What I ran
I followed the getting started document step by step, until I ran **install the Mendel Development Tool (MDT)** with
`pip3 install --user mendel-development-tool`

# What actually happened
```
Traceback (most recent call last):
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-3cyois4_/cffi-1.12.3/setup.py", line 248, in <module>
        "Programming Language :: Python :: Implementation :: PyPy",
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-3cyois4_/cffi-1.12.3/setup.py", line 248, in <module>
        "Programming Language :: Python :: Implementation :: PyPy",
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nhxeh6jk/pynacl/setup.py", line 255, in <module>
        "Programming Language :: Python :: 3.7",
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/mendel/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/mendel/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/mendel/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/mendel/.local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nhxeh6jk/pynacl/

```

# Then I update the setup-tools
`pip3 install --upgrade setuptools`
But got the same error message.

**Comment by JVTEAM** [comment]
What computer are you install MDT on?

**Comment by libo-wu** [comment]
> What computer are you install MDT on?

I use a virtual machine with Ubuntu OS to establish the serial with the TPU dev board.

**Comment by rahul4tripathi2** [comment]
better to install like this

go to your terminal and hit command line by line

# Add the repo:
echo "deb https://packages.cloud.google.com/apt coral-mdt-stable main" | sudo tee /etc/apt/sources.list.d/mdt.list

# Add Google keys
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# Then install the package:
sudo apt-get update

sudo apt-get install mendel-development-tool

https://coral.withgoogle.com/docs/dev-board/mdt/#install-mdt
