### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by Jconn** [f0cal/google-coral#48]
I'm running object detection on the edgetpu usb accelerator with the python api at 30Hz on 300x300 RGB. The function that I'm using for inference is:
`            DetectWithInputTensor(flattened_img,threshold=.1,top_k=10)
`
Every 30 seconds or so my program crashes with an error related to memory alloc/dealloc, such as:
 `munmap_chunk(): invalid pointer` or` free(): invalid next size (fast)
`

I grabbed the core dump on one crash and my callstack at the time of the exception was this:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fc7afcf9801 in __GI_abort () at abort.c:79
#2  0x00007fc7afd42897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fc7afe6fb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fc7afd4990a in malloc_printerr (str=str@entry=0x7fc7afe717a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007fc7afd50ecc in munmap_chunk (p=0x56e4970) at malloc.c:2846
#5  __GI___libc_free (mem=0x56e4980) at malloc.c:3117
#6  0x00007fc7585d7f0e in ?? () from /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
#7  0x00007fc757eaf738 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#8  0x00007fc757eb389c in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#9  0x00007fc757eb52b8 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#10 0x00007fc757eaf24c in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#11 0x00007fc757eb0130 in libusb_handle_events_timeout_completed () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#12 0x00007fc757eb022f in libusb_handle_events () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#13 0x00007fc7585da7fc in ?? () from /usr/lib/x86_64-linux-gnu/libedgetpu.so.1
#14 0x00007fc7afaa16db in start_thread (arg=0x7fc73f2c8700) at pthread_create.c:463
#15 0x00007fc7afdda88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

how can I go about debugging this further? I'm using edgetpu version '2.11.1'

**Comment by Jconn** [comment]
tried out the tensorflowlite api as described [here](https://coral.withgoogle.com/docs/edgetpu/tflite-python/) rather than the edgetpu api, and I'm no longer getting memory errors all over the place. The edgetpu python lib just isn't ready, I guess. Closing this.
