### ISSUE TITLE
Coral Enviro Sensor Board Stopped working 

### ISSUE THREAD

**Issue by kflmiami420** [f0cal/google-coral#54]
Traceback (most recent call last):
  File "/home/pi/enviro_demo-4.py", line 81, in <module>
    main()
  File "/home/pi/enviro_demo-4.py", line 62, in main
    sensors['temperature'] = enviro.temperature * (9.0 / 5.0) + 32
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

I had this line working to convert from C to F but now it says its unsupported

**Comment by kflmiami420** [comment]
another error today pi@raspberrypize10:~ $ python3 enviro_demo-4.py
No valid config provided (reading cloud_config.ini).
Cloud IoT is disabled.
Traceback (most recent call last):
  File "enviro_demo-4.py", line 81, in <module>
    main()
  File "enviro_demo-4.py", line 70, in main
    sensors['pressure'] = enviro.pressure * 10.0
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'``

**Comment by kflmiami420** [comment]
I comment the * 10 from that line    I dont get a kpa reading , The displays shows nan as a value

**Comment by Namburger** [comment]
@kflmiami420 sorry, I can't tell much just from the query, but ususally the nan errors happens when the rpi can't read/write from gpio. We've made lots of changes/bug fixes to the library. Can you check if gpio is turned on with `raspi-config` as well as installing the new library?
