### ISSUE TITLE
Deeplabv3 cityscape conversion

### ISSUE THREAD

**Issue by Valdiolus** [f0cal/google-coral#69]
Hi! 
I am looking for deeplabv3 model with cityscape pretrained, optimized for edgetpu (edgetpu.tflite) with max fps rate. 
Trying to convert from "mobilenetv3_small_cityscapes_trainfine" .pb file by myself from [url](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) but no luck - dimensions of the input of the model is surprisingly 1029*2050, and issues like this, so it doesn't work:
Number of operations that will run on Edge TPU: 2
Number of operations that will run on CPU: 124

I have tried to convert ->.tflite -> edgetpu.tflite with "mobilenetv2_dm05_coco_voc_trainaug_8bit" from here [url](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md) and it converts great! 

Can you help me with how to get deeplabv3 cityscape model 8bit?

Thank you!

**Comment by Namburger** [comment]
What command did you use to converts the deeplabv3 model?

**Comment by Tetsujinfr** [comment]
Hi @Valdiolus 
Did you manage to convert deeplabv3 for cityscape? If how did you fix your issue above?
Thanks

**Comment by Tetsujinfr** [comment]
Is there a way to get [those](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#edgetpu-deeplab-models-on-cityscapes) edgetpu pretrained cityscape models running on the USB accelerator?
Those are presented as edgetpu models, so I assume that 1) they have been quantized at training time and that I should be able to convert them to .tflite and then to compile to executable edgetpu models for the USB accelerator.

So first, I have tried to convert them to .tflite models with the std code provided[ here](https://www.tensorflow.org/lite/convert/) (recommanded way), but I have the below error message.
`RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: saved_model_cli`

My issue seems similar to [this one](https://github.com/tensorflow/tensorflow/issues/38080), but unfortunately it is still opened there.
There is some guidance in the error message, but based on the similar issue discussion it does not seem straigthfoward to solve without in depth knowledge of the pretrained model 'input_arrays' and 'output_arrays'... 


**Can you help please?** 
thanks a lot

my error log:
> edgetpu/examples$ python3 convert_pb_to_tflite.py --saved_model_dir models/edgetpu-deeplab-slim
> 2020-10-14 15:45:34.688034: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
> 2020-10-14 15:45:43.555599: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
> 2020-10-14 15:45:43.561220: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.561450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
> name: Xavier major: 7 minor: 2 memoryClockRate(GHz): 1.109
> pciBusID: 0000:00:00.0
> 2020-10-14 15:45:43.561563: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
> 2020-10-14 15:45:43.566034: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
> 2020-10-14 15:45:43.571048: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
> 2020-10-14 15:45:43.572083: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
> 2020-10-14 15:45:43.576816: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
> 2020-10-14 15:45:43.580954: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
> 2020-10-14 15:45:43.581525: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
> 2020-10-14 15:45:43.581828: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.582145: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.582246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
> 2020-10-14 15:45:43.610352: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
> 2020-10-14 15:45:43.611617: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x95f21d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-10-14 15:45:43.611767: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-10-14 15:45:43.738966: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.739507: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x9508530 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2020-10-14 15:45:43.739955: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Xavier, Compute Capability 7.2
> 2020-10-14 15:45:43.740762: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.741126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
> name: Xavier major: 7 minor: 2 memoryClockRate(GHz): 1.109
> pciBusID: 0000:00:00.0
> 2020-10-14 15:45:43.741742: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
> 2020-10-14 15:45:43.741998: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
> 2020-10-14 15:45:43.742279: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
> 2020-10-14 15:45:43.742555: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
> 2020-10-14 15:45:43.742796: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
> 2020-10-14 15:45:43.743070: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
> 2020-10-14 15:45:43.743140: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
> 2020-10-14 15:45:43.743336: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.743569: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:43.743653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
> 2020-10-14 15:45:43.743780: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
> 2020-10-14 15:45:45.839353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-10-14 15:45:45.839521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
> 2020-10-14 15:45:45.839564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
> 2020-10-14 15:45:45.840125: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:45.840499: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:950] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-14 15:45:45.840686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 94 MB memory) -> physical GPU (device: 0, name: Xavier, pci bus id: 0000:00:00.0, compute capability: 7.2)
> WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
> Traceback (most recent call last):
>   File "convert_pb_to_tflite.py", line 26, in <module>
>     main()
>   File "convert_pb_to_tflite.py", line 16, in main
>     converter = tf.lite.TFLiteConverter.from_saved_model(args.saved_model_dir) # path to the SavedModel directory
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 762, in from_saved_model
>     output_arrays, tag_set, signature_key)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert_saved_model.py", line 187, in freeze_saved_model
>     meta_graph = get_meta_graph_def(saved_model_dir, tag_set)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert_saved_model.py", line 60, in get_meta_graph_def
>     return loader.load(sess, tag_set, saved_model_dir)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
>     return loader.load(sess, tags, import_scope, **saver_kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
>     **saver_kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
>     meta_graph_def = self.get_meta_graph_def_from_tags(tags)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 327, in get_meta_graph_def_from_tags
>     "\navailable_tags: " + str(available_tags))
> RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
> available_tags: [set()]

**Comment by Valdiolus** [comment]
Hi @Tetsujinfr 
Half year ago I somehow converted deeplabV3 with cityscape to edgetpu, but there were very poor results. Today I can't find this code, but if I find, I will post it here.

**Comment by Tetsujinfr** [comment]
Thanks for your note and managing my expectations as well.  If you find the code that would be great.
When you say the results were very poor you mean the quality of the segmentation, the inference performance, both?

I find the quality of 513x513 segmantation of deeplabv3 on pascal voc 2012 not too bad given the small size of the model (although admittingly it is not great neither), and it runs at approx 7fps on my hardware setup which is a bit slow but manageable. Hence why I had hopes for Cityscape...

**Comment by Valdiolus** [comment]
The accuracy of the segmentation was bad, needed more deeply retrain the nn. Speed was quite good, but I don't remember exact fps rate.

**Comment by Tetsujinfr** [comment]
Have you tried other sementic segmentation models for outdoor/road/car classes on the edgetpu? 
E.g. I found [this](https://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2-ade20k/1/default/2) tflite small model trained on ADE20K which I thought would be a good candidate for the edgetpu, but it seems it is using float32 weights and I can not convert it to run on the coral accelerator properly. (also I am not sure of its accuracy, when I played with the collab notebook demo, the accuracy after inference was not very good, and that was not even with 8bits quantization)

**Comment by Namburger** [comment]
Hi forks - 
Sorry, just wanted to give you guys an update here, as @Valdiolus mentioned, the tflite segmentation model trained with cityscape has terrible accuracy in our test rack. This is very surprising to us and we found this out last month. Currently we are sending this to the model team to take a look.

**Comment by Tetsujinfr** [comment]
Ok thanks for the update. Looking fwd for a fix if possible on this.
About the conversion process, is there a documentation or tutorial on how to prep a .pb model file to tflite then edgetpu properly?
I came across various materials on the web (most from google/TFlow teams), but I keep getting errors when trying to convert models, even when those are advertized as "edgetpu" specific like the Cityscape one above. Not sure if I am doing something stupid but can not figure out what to do.
Can share my conversion code if that helps.

**Comment by Tetsujinfr** [comment]
hi @Namburger 
do you have any update regarding the segmentation model accuracy review by your engineering team? do you have a rough timeline on when this might be re mediated?
thanks

**Comment by Tetsujinfr** [comment]
hi, any update on the segmentation model accuracy fix on edgetpu? thanks

**Comment by Tetsujinfr** [comment]
Hi
Is there any update on the segmentation model accuracy on coral?
Thanks

**Comment by Tetsujinfr** [comment]
hi, @Namburger , do you have any update to share on this model accuracy improvement for the edge tpu? thank you
